#!/bin/sh
if [ $1 == "hdmi" ]
then 

    xrandr --output HDMI1 --auto --right-of LVDS1
    xrandr --output LVDS1 --mode 1366x768
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
    feh --bg-fill .wallpaper.jpg

elif [ $1 == "present" ]
then
    xrandr --output VGA1 --auto --same-as LVDS1
    xrandr --output VGA1 --off
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
    feh --bg-fill .wallpaper.jpg

elif [ $1 == "undock" ]
then
    xrandr --output HDMI1 --off
    xrandr --output LVDS1 --mode 1366x768
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
    feh --bg-fill .wallpaper.jpg
fi
